"""remove soft delete from item

Revision ID: b702045e8b0a
Revises: e1c262d7e2ae
Create Date: 2026-05-16 10:45:02.582088

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b702045e8b0a"
down_revision: Union[str, None] = "e1c262d7e2ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_is_deleted"), table_name="item")
    op.drop_column("item", "is_deleted")
    op.drop_column("item", "deleted_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item", sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.add_column("item", sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f("ix_item_is_deleted"), "item", ["is_deleted"], unique=False)
    # ### end Alembic commands ###
